---
# htpasswd tasks file for yauh.nginx
- name: Setup http passwords
  htpasswd: path={{ item.passwdfile }} name={{ item.name }} password={{ item.password }} owner=root group=www-data mode=0640
  with_items:
    - "{{ web_users }}"
