---
# tasks file for yauh.nginx
- name: Make sure the ansible required dependencies are installed
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - python-pycurl
    - python-pip

- name: Install python library
  pip: name=passlib

- name: Add the nginx repository
  apt_repository:
    repo: ppa:nginx/stable

- name: Install nginx
  apt: pkg=nginx state=present

- name: Configure default placeholder site
  include: defaultsite.yml
  when: nginx_setup_default_site == true

- name: Configure sites
  include: sites.yml
  when: nginx_site_configs is defined

- name: Configure SSL
  include: ssl.yml
  when: nginx_use_ssl == true

- name: Set up htpasswd access
  include: htpasswd.yml
  when:  nginx_web_users is defined

- name: Disable default config for nginx
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Finish setup and restart nginx
  service: name=nginx state=restarted
