---
# ssl tasks file for yauh.nginx
- name: Create ssl directory
  file: >
    path=/etc/nginx/ssl/
    owner=root
    group=root
    mode=0755
    state=directory

- name: Create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "{{ nginx_cert_subj }}/CN={{ nginx_cert_common_name }}" -days {{ nginx_cert_validity_duration }} -keyout {{ nginx_ssl_key_file }} -out {{ nginx_ssl_cert_file }} -extensions v3_ca creates={{ nginx_ssl_cert_file }}
  when: nginx_create_self_signed_cert

- name: Copy a file
  copy: src={{ item.src_file }} dest=/etc/nginx/ssl/{{ item.dest_name }} owner=root group=www-data mode=0640
  with_items:
    - "{{ nginx_certificate_files }}"
  when: nginx_certificate_files is defined
